openapi: 3.0.2
info:
  title: FlexMaestro Service
  description: "This is a basic FlexMaestro service, showcasing many features of a\
    \ standard Twilio Service"
  contact:
    name: Your team name goes here
    url: https://code.hq.twilio.com/your-team/flex-maestro
    email: your-team-name@twilio.com
  license:
    name: Proprietary and protected
    url: https://www.twilio.com/
  version: 1.0.0
servers:
- url: http://localhost:9876/v1
security:
- TwilioApiAuth: []
paths:
  /Admin/ReadMessages:
    get:
      tags:
      - admin
      summary: Reads all the messages
      operationId: readMessages
      parameters:
      - name: PageSize
        in: query
        description: Number of results to return at once
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          nullable: true
      - name: PageToken
        in: query
        description: Opaque token describing which page of results to return
        required: false
        style: form
        explode: true
        schema:
          type: string
          nullable: true
      responses:
        "200":
          description: Full message list
          headers:
            etag:
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloMessageList'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
      security:
      - TwilioHostAuth:
        - admin
      x-concurrency-limit:
        type: AIMD
        timeoutMs: 500
      x-rate-limit:
        default: 1
  /Service/Messages:
    get:
      tags:
      - helloMessage
      summary: Retrieves messages
      operationId: listMessages
      parameters:
      - name: From
        in: query
        description: A sender name
        required: false
        style: form
        explode: true
        schema:
          type: string
          nullable: true
      - name: To
        in: query
        description: A recipient name
        required: false
        style: form
        explode: true
        schema:
          type: string
          nullable: true
      - name: PageSize
        in: query
        description: Number of results to return at once
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          nullable: true
      - name: PageToken
        in: query
        description: Opaque token describing which page of results to return
        required: false
        style: form
        explode: true
        schema:
          type: string
          nullable: true
      responses:
        "200":
          description: Returned message list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloMessageList'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
      x-concurrency-limit:
        type: AIMD
        timeoutMs: 1500
      x-rate-limit:
        default: 10
        key: listMessages
  /Service/Messages/{sid}:
    get:
      tags:
      - helloMessage
      summary: Fetch a message
      operationId: getMessage
      parameters:
      - name: sid
        in: path
        description: A unique message SID identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
        x-jvm-type: com.twilio.sids.SmsSid
      responses:
        "200":
          description: Message returned
          headers:
            etag:
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloMessageContainer'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "404":
          description: Message not found
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
      x-etag: true
      x-concurrency-limit:
        type: AIMD
        timeoutMs: 500
      x-rate-limit:
        default: 10
    put:
      tags:
      - helloMessage
      summary: Update a message
      operationId: updateMessage
      parameters:
      - name: sid
        in: path
        description: A unique message SID identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
        x-jvm-type: com.twilio.sids.SmsSid
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                From:
                  type: string
                  description: Sender address
                  nullable: true
                To:
                  type: string
                  description: Recipient address
                  nullable: true
                Message:
                  type: string
                  description: Message body
                  nullable: true
      responses:
        "200":
          description: Message updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloMessageContainer'
        "400":
          description: Invalid parameters
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "404":
          description: Message not found
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
      x-etag: true
      x-concurrency-limit:
        type: AIMD
        timeoutMs: 500
      x-rate-limit:
        default: 1
    post:
      tags:
      - helloMessage
      summary: Create a new message
      operationId: createMessage
      parameters:
      - name: sid
        in: path
        description: A unique message SID identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
        x-jvm-type: com.twilio.sids.SmsSid
      - name: etag
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HelloMessage'
        required: true
      responses:
        "201":
          description: Message created
          headers:
            etag:
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloMessageContainer'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "422":
          description: Invalid HelloMessage
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
      x-concurrency-limit:
        type: AIMD
        timeoutMs: 500
      x-rate-limit:
        default: 1
    delete:
      tags:
      - helloMessage
      summary: Deletes a message
      operationId: deleteMessage
      parameters:
      - name: sid
        in: path
        description: A unique message SID identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
        x-jvm-type: com.twilio.sids.SmsSid
      responses:
        "204":
          description: Message deleted
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                x-jvm-type: com.twilio.rest.TwilioServiceErrorResponse
      x-concurrency-limit:
        type: AIMD
        timeoutMs: 500
      x-rate-limit:
        default: 20
components:
  schemas:
    HelloMessage:
      required:
      - from
      - message
      - to
      type: object
      properties:
        from:
          type: string
          description: The name of the sender of the message
        to:
          type: string
          description: The name of the recipient of the message
        message:
          type: string
          description: The actual message
          x-data-redaction: true
    HelloMessageContainer:
      required:
      - account_sid
      - date_created
      - date_updated
      - hello_message
      - sid
      type: object
      properties:
        sid:
          type: string
          description: The string ID reference for the message
          x-jvm-type: com.twilio.sids.SmsSid
        account_sid:
          type: string
          description: The account owning the message
          x-jvm-type: com.twilio.sids.AccountSid
        hello_message:
          $ref: '#/components/schemas/HelloMessage'
        date_created:
          type: string
          description: Timestamp of when the message was created
          format: date-time
        date_updated:
          type: string
          description: Timestamp of when the message was last updated
          format: date-time
    ListMeta:
      required:
      - key
      - page_size
      - url
      type: object
      properties:
        key:
          type: string
        page_size:
          type: integer
          format: int32
        url:
          type: string
          x-jvm-type: java.net.URI
        previous_page_url:
          type: string
          x-jvm-type: java.net.URI
        next_page_url:
          type: string
          x-jvm-type: java.net.URI
    HelloMessageList:
      required:
      - hello_messages
      - meta
      type: object
      properties:
        hello_messages:
          type: array
          description: A list of messages
          items:
            $ref: '#/components/schemas/HelloMessageContainer'
        meta:
          $ref: '#/components/schemas/ListMeta'
  securitySchemes:
    TwilioHostAuth:
      type: http
      scheme: twilio-host-auth
    TwilioApiAuth:
      type: http
      scheme: twilio-api-auth
